### ISSUE TITLE
Inquiry about Library Versions used in PINN and Thermography Processing Project

### ISSUE THREAD

**Issue by lianyichuan** [dalenhsiao/PINN-and-thermography-processing#1]
I hope this message finds you well. My name is Joey, and I recently came across your fascinating project on GitHub titled "PINN and Thermography Processing" (link: https://github.com/dalenhsiao/PINN-and-thermography-processing). First, I want to congratulate you on your work; it's impressive and incredibly relevant to my current research interests.

As I am considering utilizing your code for my project, I would like to ensure compatibility with my current setup. Could you kindly provide the specific versions of TensorFlow, NumPy, and any other critical libraries that your project depends on? Knowing the exact versions would help me avoid potential compatibility issues and ensure a smooth implementation process.

Additionally, if there are any other setup instructions or dependencies that I should be aware of, I would greatly appreciate your guidance.

Thank you very much for your time and assistance.

**Comment by dalenhsiao** [comment]
Hi Joey, 
thanks for reaching out and for your recognition. The project was built on an older version of TensorFlow, 1.15, as I recall. Regarding the NumPy version, since this project was developed some time ago, you may want to try older versions of NumPy that are compatible with TensorFlow 1.15. Feel free to reach out again if you have any follow-up questions.
